In [2]:
cd ..

/Users/yu-lin.huang/git/test-airflow

In [1]:
import pandas as pd

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [25]:
df = pd.read_csv('data/processed/lcld_v2.csv')

In [26]:
df

,loan_amnt,term,int_rate,installment,sub_grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,...,pub_rec_bankruptcies,fico_score,month_of_year,ratio_loan_amnt_annual_inc,ratio_open_acc_total_acc,month_since_earliest_cr_line,ratio_pub_rec_month_since_earliest_cr_line,ratio_pub_rec_bankruptcies_month_since_earliest_cr_line,ratio_pub_rec_bankruptcies_pub_rec,charged_off
0,4000.0,36,9.76,128.62,5,10,2,90000.0,2,2012-03-01,...,0,752.0,2,0.044444,0.600000,432,0.0,0.0,-1.0,0
1,28000.0,36,8.90,889.09,4,7,0,110000.0,1,2012-03-01,...,0,802.0,2,0.254545,0.238095,226,0.0,0.0,-1.0,1
2,7100.0,36,6.03,216.10,0,5,1,65000.0,0,2012-03-01,...,0,752.0,2,0.109231,0.300000,183,0.0,0.0,-1.0,0
3,24000.0,36,6.62,736.89,1,10,0,85000.0,2,2012-03-01,...,0,772.0,2,0.282353,0.315789,215,0.0,0.0,-1.0,0
4,6100.0,60,15.81,147.73,13,4,1,55000.0,2,2012-03-01,...,0,712.0,2,0.110909,0.520000,143,0.0,0.0,-1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220087,9600.0,36,12.98,323.37,9,10,1,75000.0,1,2018-12-01,...,0,737.0,11,0.128000,0.405405,133,0.0,0.0,-1.0,0
1220088,20000.0,36,7.02,617.73,1,0,1,97000.0,0,2018-12-01,...,0,742.0,11,0.206186,0.529412,183,0.0,0.0,-1.0,0
1220089,8500.0,36,8.19,267.11,3,0,0,75000.0,0,2018-12-01,...,0,737.0,11,0.113333,0.208333,152,0.0,0.0,-1.0,0
1220090,6000.0,36,10.33,194.54,5,10,1,54000.0,1,2018-12-01,...,0,697.0,11,0.111111,0.500000,321,0.0,0.0,-1.0,0
1220091,8425.0,36,27.27,345.18,24,3,0,450000.0,2,2018-12-01,...,0,687.0,11,0.018722,0.567568,254,0.0,0.0,-1.0,0

In [6]:
rf_parameters = {
            "n_estimators": 125,
            "min_samples_split": 6,
            "min_samples_leaf": 2,
            "max_depth": 10,
            "bootstrap": True,
            "class_weight": "balanced",
        }

In [8]:
model = RandomForestClassifier(
            **rf_parameters,
            random_state=42,
            n_jobs=1,
        )

In [27]:
df.drop('issue_d', axis=1, inplace=True)

In [28]:
feature = df.columns[:-1]

In [29]:
feature

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'sub_grade',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'purpose', 'dti', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util',
       'total_acc', 'initial_list_status', 'application_type', 'mort_acc',
       'pub_rec_bankruptcies', 'fico_score', 'month_of_year',
       'ratio_loan_amnt_annual_inc', 'ratio_open_acc_total_acc',
       'month_since_earliest_cr_line',
       'ratio_pub_rec_month_since_earliest_cr_line',
       'ratio_pub_rec_bankruptcies_month_since_earliest_cr_line',
       'ratio_pub_rec_bankruptcies_pub_rec'],
      dtype='object')

In [30]:
y = pd.factorize(df['charged_off'])[0]

In [31]:
y

array([0, 1, 0, ..., 0, 0, 0])

In [33]:
X = df[feature]

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(817461, 28) (402631, 28) (817461,) (402631,)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
...
# make predictions
yhat = model.predict(X_test)
# evaluate predictions
mae = mean_absolute_error(y_test, yhat)
print('MAE: %.3f' % mae)